[package]
name = "wio-lite-riscv"
version = "0.1.0"
authors = ["bortyr <bt324@pm.me>"]
edition = "2018"

[dependencies]
gd32vf103xx-hal = "0.4.0"
riscv = "0.6.0"
embedded-hal = "0.2.3"
nb = "0.1.2"

[dev-dependencies]
riscv-rt = "0.8.0"
panic-halt = "0.2.0"
